import type { Metadata } from "next";
import "../globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { AppBar } from "@/components";
import StoreProvider from "@/components/StoreProvider";
import MainDrawer from "@/components/Layout/Drawer/MainDrawer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					<AppBar />
					<MainDrawer />
					{children}
				</StoreProvider>
			</body>
		</html>
	);
}
